# Generated by Django 4.2.11 on 2026-03-29 08:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('computing', 'Computing'), ('exporting', 'Exporting'), ('publishing', 'Publishing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameters', models.JSONField(default=dict)),
                ('asset_raster_path', models.TextField(blank=True, null=True)),
                ('asset_vector_path', models.TextField(blank=True, null=True)),
                ('geoserver_layer', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='forest_conn_state_9cc70d_idx'), models.Index(fields=['created_at'], name='forest_conn_created_e6f7e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeoServerSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.TextField()),
                ('sync_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gs_logs', to='forest_connectivity.pipelinerun')),
            ],
        ),
        migrations.CreateModel(
            name='GEEExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('raster', 'Raster'), ('vector', 'Vector')], max_length=32)),
                ('gee_task_id', models.TextField()),
                ('status', models.CharField(default='submitted', max_length=32)),
                ('asset_path', models.TextField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gee_exports', to='forest_connectivity.pipelinerun')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'gee_task_id'], name='forest_conn_status_dfca4e_idx')],
                'unique_together': {('run', 'export_type')},
            },
        ),
    ]
